apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ex_libcluster
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: give-default-sa-libcluster
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: ex_libcluster
  apiGroup: rbac.authorization.k8s.io
---
